services:
  - type: web
    name: telegram-image-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: HF_API_TOKEN
        sync: false
